name: Workflow for leaderboard submission

on:
  # push:
    # branches: [ main ]
  # pull_request:
    # branches: [ main ]
  workflow_dispatch:
jobs:
  leaderboard:
    name: leaderboard
    runs-on:
      group: benchmark
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Configure CMake
        run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -Wno-dev

      - name: Build project
        run: |
          cmake --build build -- -j$(nproc) leaderboard
          
      - name: Run for leaderboard
        run: |
          leaderboard.sh

